### ISSUE TITLE
[BUG] Text Box WIDTH in Symbols Is Not Respected - Autoresizes Arbitrarily

### ISSUE THREAD

**Issue by luxlogica** [DWilliames/paddy-sketch-plugin#12]
In Sketch, when adding text to our artboard we can create either free text layers (by clicking with the text tool), or **text boxes** (by dragging instead of clicking). The difference between the two types of layers is:

- free text layers will extend horizontally automatically when text is added, and will auto-shrink when text is removed. If you want new lines in your text you must add them manually. Free text layers have their "Alignment" in the Type Inspector set to "Auto":
<img width="216" alt="screen shot 2018-02-10 at 8 44 37 pm" src="https://user-images.githubusercontent.com/2994472/36060747-7dcfa3f0-0ea3-11e8-8a50-9ec843f8ed83.png">

- text boxes have a **set width**: as you add text, the text will auto-wrap to the width of the box, and new lines are added automatically. Text boxes have their "Alignment" in the Type Inspector set to "Fixed":
<img width="215" alt="screen shot 2018-02-10 at 8 44 13 pm" src="https://user-images.githubusercontent.com/2994472/36060755-a4b96618-0ea3-11e8-81a2-e63c7a078b7e.png">

It seems, however, that when we have a text box (with *fixed* alignment) inside a SYMBOL, Paddy does not respect the set width of the box, and automatically resizes all text boxes HORIZONTALLY to fit the text, as if they were free text layers (with *auto* alignment). This is not the native behaviour, and gives somewhat confusing results.

To make matters worse, when we add extensive text to a symbol, Paddy seems to resize the symbol arbitrarily. I setup a simple group with 1 background rectangle (with 30px padding), and 1 text box (200px wide). So the entire symbol is supposed to be 260px. I can set it up, and define the symbol without any issues. But when I place the symbol back on the page, it autoresizes it down (because it is autoresizing the text box just wide enough to fit the default text, which is small. If I add a paragraph of text with 2 or 3 lines, it resizes the box to about 410px, and I get 2 lines of text. If I add very extensive text - line, 20 lines - it resizes the box to over 2000px. 

Although we can use Paddy's width settings to *manually* set min/max/default widths, and try to limit this autoresizing, this seems cumbersome, and not what is expected by default.

**Comment by DWilliames** [comment]
Good catch @luxlogica. I thought I made 'fixed width' stay the same width; but I must've mucked something up :P I have a decent amount of code specifically for 'fixed width' labels in Symbols; so I'll check it out.

Just to clarify your expected behaviour:
* The width should always stay in reference to the text label fixed with. So if the text layer is 200px wide, and a rectangle has a padding of 30px – all symbol instances should be stuck at a width of 260px, regardless of if the text label is only a couple of words or 5 paragraphs?
* The symbol instances should in this case only auto-resize their height; and have a fixed width of 260px?

Cheers 👍

**Comment by DWilliames** [comment]
Think I've fixed it in an upcoming version. In line with the assumptions mentioned above.

The only addition, is that it won't fix the width if the padding is set with arbitrary sides – e.g. [16 x]. 
That way, it provides the option to have 'full-width' text, but being able to resize the symbol instance on the fly.

**Comment by luxlogica** [comment]
Thank for the quick response, @DWilliames! In reply to your questions:

> ust to clarify your expected behaviour:
>
>The width should always stay in reference to the text label fixed with. So if the text layer is 200px wide, and a rectangle has a padding of 30px – all symbol instances should be stuck at a width of 260px, regardless of if the text label is only a couple of words or 5 paragraphs?

Indeed: if we set a text box (= text layer with *fixed* alignment) then the width of that layer should be kept, and extra text should add lines to it - i.e., it should grow its **height**, not its width by default. What I would expect Paddy to do here is to respect the fixed width, and adjust the background rect layer to match the new text layer's height.

> The symbol instances should in this case only auto-resize their height; and have a fixed width of 260px?

Exactly - unless the user *manually* resizes the symbol instance... ;-)

A typical example, would be when designing 'media card' elements for websites. This is how a media card symbol would normally be assembled:

![screen shot 2018-02-12 at 10 00 01 am](https://user-images.githubusercontent.com/2994472/36079837-abdf4b04-0fdb-11e8-8924-8f821d62563b.png)

...and this is what we'd expect it to show after we've added some sample dummy headline and body text:

![screen shot 2018-02-12 at 10 00 19 am](https://user-images.githubusercontent.com/2994472/36079845-c225785c-0fdb-11e8-958a-0c3d9c3d42ec.png)

**Comment by DWilliames** [comment]
@luxlogica I just pushed an update (v1.0.2) which should hopefully fix this now. Can you please verify that it works for you – then I can close this issue.

**Comment by saulodourado** [comment]
That's weird. The behavior was working fine. Now, after the update (1.0.2)  it doesn't work anymore :(

**Comment by luxlogica** [comment]
Sorry, @DWilliames, I just tested it with 1.0.2 and the problem is still there... :(

**Comment by trvsss** [comment]
Sorry, @DWilliames I just saw your last comment above and made a new issue around stacking with text boxes.

**Comment by ninstorm** [comment]
Correct I am facing the same height issue in the latest release (v1.0.4). Waiting for the fix and not re-doing any of my setup via Paddy. Thanks.

**Comment by DWilliames** [comment]
Thanks all – I'll close this issue for now around keeping the text-width with 'fixed' text layers. All further discussions around resizing to the correct height; I'll move into another issue.
